version: "2"
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "9000:80"
    links:
        - db
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
    env_file: .env
    volumes:
        - ./wp-content:/var/www/html/wp-content

  db:
    image: mysql:5.5
    env_file: .env
    volumes:
        - ./db-data:/var/lib/mysql

volumes:
  db-data:
  wp-content:
